### ISSUE TITLE
promote-all-regions not working

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/azure-extensions-cli#1]
Thanks for the great tool, and sorry if I'm not understanding this usage, but my promote-all-regions usage is failing. Looking at the code, I wonder if line 31 in promote.go needs to be changed to use checkFlag(c, regions) or something like that, instead of just regions?

**Comment by ahmetalpbalkan** [comment]
@hosungsmsft I lost the context on this but I guess it works fine now as this works just fine in EDP.

**Comment by boumenot** [comment]
Agreed.  I have not seen this issue.  I know that I have this issue, but it was my own error due to not following the appropriate promotion progression (1, 2, all).
