### ISSUE TITLE
Stuck on error: "Another operation on extension with namespace XXX, type XXX is already in progress."

### ISSUE THREAD

**Issue by hush-hush** [Azure/azure-extensions-cli#14]
Hi,

When I tried to upload a new version of my extension I got a 404:

```
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
<Code>ConflictError</Code>
<Message>Another operation on extension with namespace XXX, type XXX is already in progress.</Message>
</Error>
```

Or if I check my current operation calling: "https://management.core.windows.net/<SUBSCRIPTION_ID>/operations?StartTime=2017-08-01&EndTime=2017-12-01", all my request are liste as `Failed` or `Succeeded` (no `InProgress`) and all have an `OperationCompletedTime`.

How can I leave this state ?

Thanks.

**Comment by boumenot** [comment]
I am not sure I understand your issue, please clarify.  Why are you logging an issue against the CustomScript extension for a new version of your extension?

**Comment by hush-hush** [comment]
Because we used the azure-extensions-cli to push a new version of our extension and end-up in that state.

If this isn't the right place, can you redirect me ?

**Comment by boumenot** [comment]
My bad.  I lost track of the GitHub repository I was looking at.  You have the correct repository.

The error message you get is expected (albeit annoying).  The correct response is to retry until the requested is accepted.  The platform does not queue the request for you, so keep trying.

**Comment by hush-hush** [comment]
Thanks for the answer !

I retried for the last day and an half now and nothing changed. Can you look at why the azure platform is stuck or redirect me to the right person ?

**Comment by boumenot** [comment]
I raised an incident yesterday.  We have several publish jobs that have been waiting a long time to complete.  There is no SLA on publishing, so the only response is the interim is to retry.

No, I am not the right person, nor is the correct forum.  

If you're internal, you should be using ICM to raise the issue.
If you're external, you should be working with your contact to work the issue.

If you're neither of these, then you'll have no recourse, which is not acceptable, so I guess this is _right_ forum. 😄 If you do not have a contact I will get you one.

**Comment by hush-hush** [comment]
The API unlock itself this morning and I was able to publish a new version worldwide.
I asked internally for our contact point within azure for next time (we should have one).

Thanks for the help !
