### ISSUE TITLE
Latest code build fails

### ISSUE THREAD

**Issue by preranakhare123** [Azure/azure-extensions-cli#15]
Tried to build latest code today, it fails -

azure-extensions-cli]# go build
# _/home/pkhare/azure/new_azure_extension_cli/src/azure-extensions-cli
./publish.go:112: bs.CreateContainerIfNotExists undefined (type storage.BlobStorageClient has no field or method CreateContainerIfNotExists)
./publish.go:116: bs.CreateBlockBlobFromReader undefined (type storage.BlobStorageClient has no field or method CreateBlockBlobFromReader)
./publish.go:119: bs.GetBlobURL undefined (type storage.BlobStorageClient has no field or method GetBlobURL)

**Comment by boumenot** [comment]
No, the build is working fine.  It is checked by CI.  I pushed a no-op build through to verify it is working, see #16 for success.

I do not want you to have to build the code.  I need to ensure there isn't an impact to me pushing a new release with changes to the command line parameters.  Once I have verified that I'll push a new release.
