### ISSUE TITLE
Deployment of Marketplace Package

### ISSUE THREAD

**Issue by baichinger** [Azure/azure-extensions-cli#32]
Is it possible to use `azure-extensions-cli` to deploy [Azure Marketplace Packages](https://github.com/Azure/azure-marketplace/wiki/Publishing-a-Virtual-Machine-Extension-to-Marketplace)? The process describe at https://github.com/Azure/azure-marketplace/wiki/Publishing-a-Marketplace-Package-for-Virtual-Machine-Extensions seems outdated.

**Comment by boumenot** [comment]
No.  This CLI is only used for publishing extensions not images.

/cc: @danielsollondon - do you have any ideas on how to route @baichinger for assistance?
